import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const workflowThemeInitScript = `
  try {
    var raw = localStorage.getItem("workflow-ui-store");
    var parsed = raw ? JSON.parse(raw) : null;
    var theme = parsed && parsed.state && parsed.state.theme;
    if (theme === "light" || theme === "dark") {
      document.documentElement.setAttribute("data-workflow-theme", theme);
    }
  } catch (error) {}
`;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        suppressHydrationWarning
      >
        <head>
          <Script id="workflow-theme-init" strategy="beforeInteractive">
            {workflowThemeInitScript}
          </Script>
        </head>
        <body className="min-h-full flex flex-col">{children}</body>
      </html>
    </ClerkProvider>
  );
}
